### ISSUE TITLE
base.js里面的addStorageField方式所修改的信息和主页的核酸检测结果不一致

### ISSUE THREAD

**Issue by everyonelovesCCP** [ilovexjp/skm-simulator#1]
也就是detail.html页面里面的核酸检测的时间和外面主页生成的核酸检测不一致，如果对方要求拍照则有概率被发现。
还有采样点在修改之后，主页的也没有变化，仅仅变化了detail页面的。

还有一个可能会影响的小bug，如果运行在非root界面才会发生：
detail.html里面的导入base.js的链接有误，不应该加../而且应该
<script src="common/base.js">

**Comment by everyonelovesCCP** [comment]
还有index里面的json文件导入前面也要加个/

**Comment by ilovexjp** [comment]
采样点无法修改的问题已经修复。核酸检测时间是随机生成的，暂时没有做存储，可能未来会支持存储及/或自定义核酸检测记录。

路径的问题是打包的时候没有特殊处理的缘故，已经更新带有行程卡和目录的源码，应该不会再出现问题了。`manifest.json` 的想法是每个子项目都可以有独立的 Web App，所以 `index.html` 页只需要引入当前路径下的 `manifest.json`。
