### ISSUE TITLE
detail里面的48小时显示可以更新一下嘛

### ISSUE THREAD

**Issue by everyonelovesCCP** [ilovexjp/skm-simulator#2]
![AC199021-4976-4EA0-9DCD-B3F928A6CD27](https://user-images.githubusercontent.com/71995715/198823395-a5a16358-9878-438c-bc1f-0ae452483545.jpeg)
如果可以还请更新一下detail里面的48小时的绿框显示，感谢

**Comment by ilovexjp** [comment]
请更新一下源代码，这个显示已经更新了。

还有这张图暴露的个人信息有点多，不管是不是你自己的，都建议删除。
